// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEnvironment(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddEnvironment'](arg1, arg2, arg3, arg4, arg5);
}

export function AddRule(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddRule'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddService(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddService'](arg1, arg2, arg3);
}

export function AutoBootstrap() {
  return window['go']['main']['App']['AutoBootstrap']();
}

export function CheckGateway() {
  return window['go']['main']['App']['CheckGateway']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CheckUpdateDetail() {
  return window['go']['main']['App']['CheckUpdateDetail']();
}

export function ConfigPath() {
  return window['go']['main']['App']['ConfigPath']();
}

export function ConnectRegistry() {
  return window['go']['main']['App']['ConnectRegistry']();
}

export function DeleteManualServices() {
  return window['go']['main']['App']['DeleteManualServices']();
}

export function DeleteRule(arg1, arg2) {
  return window['go']['main']['App']['DeleteRule'](arg1, arg2);
}

export function DeleteService(arg1) {
  return window['go']['main']['App']['DeleteService'](arg1);
}

export function EditRule(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['EditRule'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function ExportEnvironment(arg1) {
  return window['go']['main']['App']['ExportEnvironment'](arg1);
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportConfig() {
  return window['go']['main']['App']['ImportConfig']();
}

export function OpenConfigDir() {
  return window['go']['main']['App']['OpenConfigDir']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PreviewYAML() {
  return window['go']['main']['App']['PreviewYAML']();
}

export function PullServices() {
  return window['go']['main']['App']['PullServices']();
}

export function RemoveEnvironment(arg1) {
  return window['go']['main']['App']['RemoveEnvironment'](arg1);
}

export function RenameEnvironment(arg1, arg2) {
  return window['go']['main']['App']['RenameEnvironment'](arg1, arg2);
}

export function ReorderRules(arg1, arg2) {
  return window['go']['main']['App']['ReorderRules'](arg1, arg2);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function SaveRegistry(arg1) {
  return window['go']['main']['App']['SaveRegistry'](arg1);
}

export function SetAllRules(arg1, arg2) {
  return window['go']['main']['App']['SetAllRules'](arg1, arg2);
}

export function SetAllServices(arg1) {
  return window['go']['main']['App']['SetAllServices'](arg1);
}

export function SetAllowLAN(arg1) {
  return window['go']['main']['App']['SetAllowLAN'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['main']['App']['SetCtx'](arg1);
}

export function SetDefaultTarget(arg1, arg2) {
  return window['go']['main']['App']['SetDefaultTarget'](arg1, arg2);
}

export function SetGateway(arg1) {
  return window['go']['main']['App']['SetGateway'](arg1);
}

export function SetLang(arg1) {
  return window['go']['main']['App']['SetLang'](arg1);
}

export function SetPort(arg1) {
  return window['go']['main']['App']['SetPort'](arg1);
}

export function SetProbeInterval(arg1) {
  return window['go']['main']['App']['SetProbeInterval'](arg1);
}

export function SetServicePrefix(arg1, arg2) {
  return window['go']['main']['App']['SetServicePrefix'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function SwitchEnvironment(arg1) {
  return window['go']['main']['App']['SwitchEnvironment'](arg1);
}

export function ToggleRule(arg1, arg2) {
  return window['go']['main']['App']['ToggleRule'](arg1, arg2);
}

export function ToggleRuleStrip(arg1, arg2) {
  return window['go']['main']['App']['ToggleRuleStrip'](arg1, arg2);
}

export function ToggleService(arg1) {
  return window['go']['main']['App']['ToggleService'](arg1);
}
