// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {core} from '../models';
import {version} from '../models';
import {context} from '../models';

export function AddEnvironment(arg1:string,arg2:model.Registry,arg3:string,arg4:number,arg5:string):Promise<void>;

export function AddRule(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<void>;

export function AddService(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AutoBootstrap():Promise<void>;

export function CheckGateway():Promise<core.CheckResult>;

export function CheckUpdate():Promise<string>;

export function CheckUpdateDetail():Promise<version.CheckUpdateResult>;

export function ConfigPath():Promise<string>;

export function ConnectRegistry():Promise<void>;

export function DeleteManualServices():Promise<void>;

export function DeleteRule(arg1:string,arg2:number):Promise<void>;

export function DeleteService(arg1:string):Promise<void>;

export function DownloadAndUpdate(arg1:string):Promise<void>;

export function EditRule(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number,arg6:string,arg7:string):Promise<void>;

export function ExportConfig():Promise<string>;

export function ExportEnvironment(arg1:string):Promise<string>;

export function GetLocalIP():Promise<string>;

export function GetLogs():Promise<Array<model.LogEntry>>;

export function GetVersion():Promise<string>;

export function ImportConfig():Promise<void>;

export function OpenConfigDir():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PreviewYAML():Promise<string>;

export function PullServices():Promise<core.ConnectResult>;

export function RemoveEnvironment(arg1:string):Promise<void>;

export function ReorderRules(arg1:string,arg2:Array<number>):Promise<void>;

export function ResetConfig():Promise<void>;

export function SaveConfig():Promise<void>;

export function SaveRegistry(arg1:model.Registry):Promise<void>;

export function SetAllRules(arg1:string,arg2:boolean):Promise<void>;

export function SetAllServices(arg1:boolean):Promise<void>;

export function SetAllowLAN(arg1:boolean):Promise<void>;

export function SetCtx(arg1:context.Context):Promise<void>;

export function SetDefaultTarget(arg1:string,arg2:string):Promise<void>;

export function SetGateway(arg1:string):Promise<void>;

export function SetPort(arg1:number):Promise<void>;

export function SetProbeInterval(arg1:number):Promise<void>;

export function SetServicePrefix(arg1:string,arg2:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function Snapshot():Promise<core.Snapshot>;

export function StartProxy():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopProxy():Promise<void>;

export function SwitchEnvironment(arg1:string):Promise<void>;

export function ToggleRule(arg1:string,arg2:number):Promise<void>;

export function ToggleRuleStrip(arg1:string,arg2:number):Promise<void>;

export function ToggleService(arg1:string):Promise<void>;
